server:
  port: 8089
apollo:
  # 开启缓存 大量配置下可大幅度提升更新速度
  property:
    names:
      cache:
        enable: true
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: test-apollo, test-user
  meta: http://127.0.0.1:8081
  cache-dir: E:\i-works\Apollo\cache
  cluster: default

user:
  username: zhangsan
  age: 15
  sex: 男

listeners: test-apollo, test-user, application


